# PostgreSQL. Versions 8.2 and up are supported.

common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost

development:
  <<: *common
  database: excel_import_development

test:
  <<: *common
  database: excel_import_test

production:
  <<: *common
  database: excel_import
